services:

    carbon:
        class: Carbon\Carbon
        public: true
        calls:
            - ['setLocale', ['%carbon.default_locale%']]

    mnc_doctrine_carbon.listener:
        class: MNC\DoctrineCarbonBundle\Doctrine\CarbonDateListener
        arguments:
            - '@carbon'
            - '@logger'
            - '%mnc_doctrine_carbon.properties%'
            - '%mnc_doctrine_carbon.excluded_entities%'
        tags:
            - { name: doctrine.event_subscriber }